quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET, POST, PUT, DELETE

frontend.url=${FRONTEND_URL}

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

%prod.quarkus.hibernate-orm.database.generation=none
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=false

quarkus.http.root-path=/api

app.jwt.secret=REPLACE_WITH_SECURE_RANDOM_BASE64_OR_32_CHAR_STRING
app.jwt.ttl-ms=3600000

quarkus.package.jar.type=uber-jar

quarkus.mailer.host=${MAIL_HOST}
quarkus.mailer.port=587
quarkus.mailer.username=${MAIL_USER}
quarkus.mailer.password=${MAIL_PASSWORD}
quarkus.mailer.auth-methods=PLAIN

media.bucket=teacherhelper-media-prod