insert into app_user (
    id,
    username,
    email,
    password,
    subscription_model,
    email_verified,
    allow_invitations,
    profile_image_url,
    locked,
    created_at,
    last_activity_at
) values
      (
          gen_random_uuid(),
          'admin',
          'admin@admin',
          '$2a$10$Rp61DZDWDgUwUObAkBxfYueUfvrDidwM5lILMCJ.WyiTMYonnGQKi',
          'ADMIN',
          true,
          true,
          'users/1/avatar/current.jpg',
          false,
          now(),
          now()
      ),
      (
          gen_random_uuid(),
          'user',
          'user@user',
          '$2a$10$Rp61DZDWDgUwUObAkBxfYueUfvrDidwM5lILMCJ.WyiTMYonnGQKi',
          'FREE',
          true,
          true,
          'users/2/avatar/current.jpg',
          false,
          now(),
          now()
      );